# NUMPY


## installing Numpy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


### Creating 1-D array

In [2]:
x= np.array([10,20,30,40])

NameError: name 'np' is not defined

In [3]:
import numpy as np
x=np.array([10,20,30,40])

In [4]:
y=np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [6]:
! import numpy as np

'import' is not recognized as an internal or external command,
operable program or batch file.


In [7]:
! import numpy as np
y=np.array([[1,2,3],[4,5,6]])


'import' is not recognized as an internal or external command,
operable program or batch file.


In [11]:
import numpy as np

In [9]:
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [10]:
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Pandas

### used for data manipulation and analysis

In [12]:
! pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.0 MB 15.9 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.0 MB 22.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 22.4 MB/s  0:00:00

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ------------------

In [13]:
import pandas as pd

In [15]:
s = pd.Series([10,20,30,40],
 name = "MyNumbers")
print(f"Pandas Series:\n{s}")
print(f"Type of Series:{type(s)}")

Pandas Series:
0    10
1    20
2    30
3    40
Name: MyNumbers, dtype: int64
Type of Series:<class 'pandas.core.series.Series'>
